trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Npm@1
  - script: npm install -f
    workingDirectory: backend/
    displayName: "npm install on backend"

  - script: npm install
    workingDirectory: frontend/
    displayName: "npm install on frontend"

  - script: npm run build
    workingDirectory: frontend/
    displayName: "npm build on frontend"

  - script: npm run-script test-ci
    workingDirectory: backend/
    displayName: "Execute unit tests"
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/junit.xml"
      mergeTestResults: true
      testRunTitle: "Jest Unit Tests"
      failTaskOnFailedTests: true

  - task: CopyFiles@2
    inputs:
      targetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
